#!/bin/bash
# Regenerates the IANA time-zone -> ISO 3166-1 alpha-2 region table from the
# system's canonical tz database (/usr/share/zoneinfo/zone.tab). This is data,
# not logic: the flag emoji for a clock is derived from its region at runtime.
# Usage: scripts/make-regions.sh
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=/usr/share/zoneinfo/zone.tab
OUT=Sources/MeantimeKit/Formatting/TimeZoneRegions.swift
[ -f "$SRC" ] || { echo "missing $SRC"; exit 1; }

{
  echo "// Generated by scripts/make-regions.sh from $SRC — do not edit by hand."
  echo "// Maps an IANA time-zone identifier to its ISO 3166-1 alpha-2 region code."
  echo "// The region is turned into a flag emoji at runtime (see RegionFlag)."
  echo ""
  echo "enum TimeZoneRegions {"
  echo "    static let byIdentifier: [String: String] = ["
  grep -vE '^#' "$SRC" | awk -F'\t' 'NF>=3 && $1 ~ /^[A-Z][A-Z]$/ {print $3"\t"$1}' \
    | sort \
    | awk -F'\t' '{printf "        \"%s\": \"%s\",\n", $1, $2}'
  echo "    ]"
  echo "}"
} > "$OUT"

echo "wrote $OUT ($(grep -c ': ' "$OUT") entries)"
